function denosing_signal = denoising(y)

% Decompose signal using the MODWT

% Generated by MATLAB(R) 24.1 and Wavelet Toolbox 24.1.
% Generated on: 08-11月-2024 03:58:40

% Logical array for selecting reconstruction elements
levelForReconstruction = [false,false,false,false,true];

% Perform the decomposition using modwt
wt = modwt(y,'db6',4);

% Construct MRA matrix using modwtmra
mra = modwtmra(wt,'db6');

% Sum down the rows of the selected multiresolution signals
y1 = sum(mra(levelForReconstruction,:),1);

denosing_signal = y1;

end
